Get composer file
hackathon-21-spring-02/back-end pull request #41
Opened 2021-06-19 16:48 UTC by xxarupakaxx

`composers/composerID/files`でそのComposerのファイル情報を出力できるようにした

2021-06-19 20:50 UTC, Ras96 requested changes
いくつかコメントしました:metal:

2021-06-19 20:50 UTC, ras0q commented on domain/composer.go
> +}
これ`File`使えばおっけーです
(swaggerでもどっちも同じschemaを使ってる http://main.back-end.hackathon21_spring_02.trap.show/openapi/#/composer/getComposerFiles)

2021-06-19 20:50 UTC, Ras96 commented on model/composer.go
> +	composer, _ := GetComposer(ctx, accessToken, composerID)
useridとnameのペア取るだけならapi叩いた方が早いですね
#43 と同じ感じで実装できそう

2021-06-20 00:54 UTC, xxarupakaxx reviewed
よさそう

2021-06-20 00:54 UTC, Ras96 approved these changes

2021-06-20 01:04 UTC, merged