監視用traQbotの作成
hackathon-21-spring-02/back-end pull request #54
Opened 2021-06-24 13:27 UTC by Ras96

テストしてないです

2021-06-25 04:44 UTC, SSlime-s reviewed
動作確認してない
ちょっと気になったとこだけ

2021-06-25 04:44 UTC, SSlime-s commented on router/bot/handler.go
> +		}
編集・削除も見たほうが

2021-06-25 14:59 UTC, Ras96 commented
どっちも追加しました
一応sql文のテストだけはした
削除のときの実装がカスそうなので見てほしい

2021-06-26 17:08 UTC, SSlime-s reviewed
ちょっと

2021-06-26 17:08 UTC, SSlime-s commented on model/file.go
> +func DeleteFiles(ctx context.Context, messageID string) error {
きもいかも
```suggestion
func DeleteFilesFromMessageId(ctx context.Context, messageID string) error {
```

2021-06-26 17:08 UTC, SSlime-s commented on router/bot/message_updated.go
> +				return err
まとめて Insert Delete してほしい

2021-06-26 17:08 UTC, SSlime-s commented on router/bot/util.go
> +func removeExt(str string) string {
略語使わないほうが:yosa:

2021-07-03 04:54 UTC, SSlime-s requested changes
ちょっと

2021-07-03 04:54 UTC, SSlime-s commented on model/file.go
> +			"VALUES (:id, :title, :composer_id, :composer_name, :message_id, :created_at)",
ここ分けてる意味あるの？

2021-07-03 04:54 UTC, SSlime-s commented on router/bot/message_created.go
> +			err = model.InsertFiles(ctx, insertReq)
ループの中で叩いたらだめでは

2021-07-03 04:54 UTC, SSlime-s commented on router/bot/message_updated.go
> +			err = model.InsertFiles(ctx, insertReq)
ここも

2021-07-03 13:04 UTC, Ras96 commented on model/file.go
> +			"VALUES (:id, :title, :composer_id, :composer_name, :message_id, :created_at)",
長かったからしか理由ないけどバッククォートで書いた方が良さそう
一行はさすがに見にくくない？
https://stackoverflow.com/questions/36244767/long-queries-in-golang

2021-07-03 13:07 UTC, SSlime-s commented on model/file.go
> +			"VALUES (:id, :title, :composer_id, :composer_name, :message_id, :created_at)",
はい `` ` ``使ってもろて
複数行に分けるために `+` 使うの違くないか という主張でもあった

2021-07-03 13:33 UTC, Ras96 commented
なおした

2021-07-06 14:37 UTC, SSlime-s reviewed
ちょっと

2021-07-06 14:37 UTC, SSlime-s commented on model/file.go
> +
`` ` `` だけの行から始まるの :yaya: だけど見やすいからいいといえばいい
(好み)

2021-07-06 14:37 UTC, SSlime-s commented on model/file.go
> +		query,
ここ別に直接書いてもいいのではと思ってしまった

2021-07-06 14:37 UTC, SSlime-s commented on router/bot/message_updated.go
> +	deleteReq := make([]string, 0, len(oldArr)) // 削除するメッセージの配列
メッセージの配列ではなくないか
あと自明なコメントはなくても良い気がする + Req って変数名ちょっと :yaya: じゃない？
deleteFileIds (これは長いけど) とかのが良い気がせん？

2021-07-06 15:16 UTC, Ras96 commented
@SSlime-s 
なおした(時計ずれててコミットとコメントの順番おかしいことになってるけど)

2021-07-06 16:13 UTC, SSlime-s commented on router/bot/message_updated.go
> +	deleteFields := make([]string, 0, len(oldArr))
ここでの Fields ってどういう意味？

2021-07-07 03:18 UTC, Ras96 commented on router/bot/message_updated.go
> +	deleteFields := make([]string, 0, len(oldArr))
deleteFileIdsと見間違えてた:weary:

2021-07-07 03:37 UTC, Ras96 commented
なおした

2021-07-07 03:43 UTC, SSlime-s approved these changes
過去の自分を信じて

2021-07-07 04:20 UTC, merged