🐛 ファイルがnon seekableだった
hackathon-21-spring-02/back-end pull request #67
Opened 2021-07-13 20:32 UTC by Ras96

多分一番の原因は`file.Close()`してなかったこと
ローカルで3件くらいしか試してないので時間あったらもう少し試してみるけどおおよそ改善したはず
いきなり2:00とかに飛ぶと一瞬止まるけどまあそれは仕様:kana-:

2021-07-13 20:32 UTC, Ras96 commented
Closes #67

2021-07-13 20:44 UTC, SSlime-s requested changes
寝れんかった
動作確認はしてない

2021-07-13 20:44 UTC, SSlime-s commented on router/file.go
> +	// return c.Stream(http.StatusOK, res.Header.Get("Content-Type"), file)
消してもろて

2021-07-13 20:44 UTC, SSlime-s commented on model/file.go
> +func GetFileDownload(ctx context.Context, fileID string, accessToken string) (*os.File, *File, *http.Response, error) {
ここまででかくなるなら構造体にして構造体返したほうが良くないか

2021-07-14 02:06 UTC, Ras96 commented
@SSlime metaの取得いらなかった
ファイル名`download.mp3`とかになるけどまあそこはどうでも良さそう

2021-07-14 03:00 UTC, SSlime-s approved these changes
動くなら :yosa;

2021-07-14 03:15 UTC, merged