GetComposer()の実装
hackathon-21-spring-02/back-end pull request #9
Opened 2021-06-16 13:33 UTC by xxarupakaxx

GetCompose()を実装してみました

2021-06-17 03:27 UTC, Ras96 requested changes

2021-06-17 03:27 UTC, Ras96 commented on model/composers.go
> +	const soundChannelId="8bd9e07a-2c6a-49e6-9961-4f88e83b4918"
ここら辺は`file.go`とかでも使うと思うので`model/util.go`を作成してそこに書いておくといいと思います

2021-06-17 03:27 UTC, Ras96 commented on model/composers.go
> +	v.Set("mine","false")
ここはchannelIDとlimitだけでよさそうです

2021-06-17 03:27 UTC, Ras96 commented on model/composers.go
> +	uStr:=u.String()*/
ここは https://github.com/hackathon-21-spring-02/back-end/blob/main/router/oauth.go#L186-L187 みたいな感じで書くといいと思います。https://github.com/hackathon-21-spring-02/back-end/blob/main/router/oauth.go#L20 で既にbaseUrlをパースしてて、`/files`足すだけなのでまあ今回はエラーハンドリングしなくていいと思います。(上で伝えたutil.goに書くbaseUrlも#L20みたいに書くのがいいと思います)

2021-06-17 03:27 UTC, Ras96 commented on model/composers.go
> +	//TODo:ここやばい？
多分大丈夫そう
それとdataはmakeで作る方が良さそうです(newだと初期化がされないらしい？よくわかってないけどmakeの方が一般的な気がする)

2021-06-17 03:27 UTC, Ras96 commented
@xxarupakaxx コメントしました:pray:

2021-06-17 03:44 UTC, xxarupakaxx commented on model/composers.go
> +	//TODo:ここやばい？
わかりました！レビューありがとうございます
修正しておきます

2021-06-17 14:00 UTC, xxarupakaxx commented
様々な修正とかGetComposers()の返り値をUploaderIDを返すようにしました

2021-06-17 18:38 UTC, Ras96 requested changes
いくつかコメントしました:raised_hands:

2021-06-17 18:38 UTC, Ras96 commented on model/composers.go
> +	v.Set("channelId",soundChannelId)
`v.Set`だとBodyにセットしちゃうのでたぶんリクエストが通らないです
`/model/file.go`を参考にして貰いたいのですが、`req.URL.Query`でクエリパラメータを設定できます

アクセストークンも必要なのでrouter/file.goで取得して引数で渡すのがいいと思います:metal:

2021-06-17 18:38 UTC, Ras96 commented on model/composers.go
> +
ここ消しちゃってください:love_you_gesture:
```suggestion
	for _,r:=range data{
		result[r.UploaderID]=r.Name
	}
	return result,err
}
```

2021-06-17 18:38 UTC, Ras96 commented on model/composers.go
> +func GetComposers() (map[string]string,error){
ここの返り値は↓のようにしてほしいです:pray:
http://main.back-end.hackathon21_spring_02.trap.show/openapi/#/composer/getComposers

2021-06-17 18:38 UTC, Ras96 commented on router/composes.go
> +}
ファイルの最後は改行入れてください:metal:
```suggestion
}

```

2021-06-17 18:38 UTC, Ras96 commented on router/composes.go
> +
ここら辺もrouter/file.goを参考に実装してほしいです:+1:

2021-06-18 11:38 UTC, xxarupakaxx commented on router/composes.go
> +}
完了

2021-06-18 11:38 UTC, xxarupakaxx commented on model/composers.go
> +func GetComposers() (map[string]string,error){
一度プルりく出したときに見てほしいです

2021-06-18 11:38 UTC, xxarupakaxx commented on model/composers.go
> +
完了

2021-06-18 11:54 UTC, xxarupakaxx commented on model/composers.go
> +	v.Set("channelId",soundChannelId)
`router/file.go`で取得がよくわからなかったので今日の集会で聞きます

2021-06-18 11:54 UTC, xxarupakaxx commented on router/composes.go
> +
PR確認よろしくお願いします

2021-06-18 12:00 UTC, Ras96 requested changes

2021-06-18 12:00 UTC, Ras96 commented on router/composes.go
> +	userID:=sess.Values["id"].(string)
多分この実装でユーザー依存なものはないのでuserIDいらなそうです

2021-06-18 12:39 UTC, Ras96 requested changes
いくつかコメントしました

2021-06-18 12:39 UTC, Ras96 commented on model/composers.go
> +}
ここ僕がいきなり方針変えたのであれなんですが、これdomainに書いてくれると助かります
mainのやつ→https://github.com/hackathon-21-spring-02/back-end/blob/main/domain/file.go

2021-06-18 12:39 UTC, Ras96 commented on model/composers.go
> +	params.Add("channelId","8bd9e07a-2c6a-49e6-9961-4f88e83b4918")
ここ文字列そのままじゃなくてutilの変数使ってほしいです:pray:

2021-06-18 12:39 UTC, Ras96 commented on model/composers.go
> +func GetComposers(ctx context.Context,accessToken string,composerId string) ([]Composers,error){
返り値`([]*Composers, error)`にしてほしいです:pray:

2021-06-18 12:39 UTC, Ras96 commented on model/composers.go
> +	}
composersの作成は`make([]*Composers, 0, len(data))`の方がいいです(長さ0、キャパlenのスライスができます)
要素の追加は`append`を使うのが良さそうです(これだとなんか範囲外エラー出た)

2021-06-18 15:10 UTC, Ras96 requested changes

2021-06-18 15:10 UTC, Ras96 commented on domain/file.go
> +}
これ一つは1要素なので`Composer`にしてほしいです

2021-06-18 15:15 UTC, xxarupakaxx commented on domain/file.go
> +}
完了

2021-06-18 16:00 UTC, xxarupakaxx commented
`model/getcomposers()`の部分のstruct名を変えておくのを忘れていた

2021-06-18 18:50 UTC, Ras96 commented
model/composers.goとrouter/composes.goはcomposer.goにしてほしいです:pray:

2021-06-18 19:03 UTC, Ras96 commented
手元で動作確認してたら結構デカい変更が必要そうでした
ちゃんと確認できて申し訳ないです:bow::bow::bow::bow::bow:

現状このエンドポイントを叩いて返ってくるのは
```
{
  "id": 投稿者のuuid,
  "name": 曲名,
  "post_num": 0
]
```
だと思うんですが、返してほしいのは
```
{
  "id": 投稿者のuuid,
  "name": 投稿者名,
  "post_num": 投稿数
]
```
ですね、、

これを実装するには
1. traQの`GET /users`からユーザー一覧を取得
2. 1からuuidとnameの組のmapを作る
3. traQの`GET /files`からファイル情報を取得
4. 3から各投稿者の投稿数を数える(これもmapで行けそう)
5. 2,4からレスポンスを作る

みたいな感じがいいと思います

できることは手伝うのでお願いします:pray:

2021-06-19 02:23 UTC, xxarupakaxx commented
もしかして取ってきた https://github.com/hackathon-21-spring-02/back-end/blob/e4a0c3070294051b304852bae180072f1d653a6b/model/composer.go#L53
ここのdataって使わない..?

2021-06-19 02:33 UTC, Ras96 commented
postCountを計算するときに必要かな
https://ashitani.jp/golangtips/tips_map.html#map_HasKey とかでpostCountを計算するmapにすでにcomposerIDがあればインクリメント、なければ1で初期化みたいな感じで計算できそう

2021-06-19 02:34 UTC, Ras96 commented
`//TODO: データベースからとってくるようにする`も嘘ですね、これはapi叩くたびに計算しそう:bow:

2021-06-19 03:29 UTC, Ras96 commented
↑を計算するときに、
https://github.com/hackathon-21-spring-02/back-end/blob/main/model/file.go#L74-L85 
みたいな感じでaudioファイルのときだけインクリメントみたいな感じにしてほしいです:pray:

2021-06-19 08:48 UTC, xxarupakaxx commented
これでいける！

2021-06-19 09:20 UTC, Ras96 requested changes
一点だけ:pray:

2021-06-19 09:20 UTC, Ras96 commented on model/composer.go
> +	composers := make([]*domain.Composer, 0, len(users))
ここ調べたら普通にインクリメントするのが推奨らしい
https://staticcheck.io/docs/checks#S1036

2021-06-19 09:25 UTC, xxarupakaxx commented on model/composer.go
> +	composers := make([]*domain.Composer, 0, len(users))
ありがと～！
完了

2021-06-19 09:26 UTC, xxarupakaxx commented
offsetも考慮すべきだと気づいたのでそこのところやっておきます

2021-06-19 11:44 UTC, Ras96 requested changes

2021-06-19 11:44 UTC, Ras96 commented on model/composer.go
> +	users, res, err := client.UserApi.GetUsers(auth,&traq.UserApiGetUsersOpts{IncludeSuspended: optional.NewBool(true)})
少なくても今回に関しては凍結ユーザーはいらなそう(クライアント側の実装見ないと分からないけど)

2021-06-19 12:35 UTC, Ras96 commented on model/composer.go
> +	users, res, err := client.UserApi.GetUsers(auth,&traq.UserApiGetUsersOpts{IncludeSuspended: optional.NewBool(true)})
ほしいらしい

2021-06-19 12:35 UTC, Ras96 approved these changes
:LGTM:

2021-06-19 12:36 UTC, Ras96 requested changes
の前にLinterかけてもらっていいですか:bow:

2021-06-19 12:49 UTC, xxarupakaxx commented
lintしました！

2021-06-19 12:51 UTC, Ras96 approved these changes

2021-06-19 12:51 UTC, merged